#pragma once

#include "gamedefs.h"

#define MAX_SPRITES 1000



enum SpriteSheetID {
    SPRITE_APPRENTICE,
    SPRITE_NERD,
    SPRITE_CROSSHAIR,
    SPRITE_WAND,
    SPRITE_MAIN,
    SPRITE_NUM_SPRITES
};

extern Texture2D g_sprite_sheets[MAX_SPRITES];

enum UISpriteID {
    UI_ID_CROSSHAIR,
};

extern Texture2D g_ui_sprites[MAX_SPRITES];

enum ItemID {
    ITEM_ID_NONE = -1,
    ITEM_ID_DAGGER,         
    ITEM_ID_SWORD,
    ITEM_ID_SPEAR,
    ITEM_ID_AXE,
    ITEM_ID_BOW,

    ITEM_ID_MAGICMISSLE_WAND_1,           
    ITEM_ID_MAGICMISSLE_WAND_2,
    ITEM_ID_MAGICMISSLE_WAND_3,
    ITEM_ID_FIREBALL_WAND_1,           
    ITEM_ID_FIREBALL_WAND_2,
    ITEM_ID_FIREBALL_WAND_3,
    ITEM_ID_LIGHTNING_WAND_1,           
    ITEM_ID_LIGHTNING_WAND_2,
    ITEM_ID_LIGHTNING_WAND_3,

    ITEM_ID_MAGICMISSLE_STAFF_1,           
    ITEM_ID_MAGICMISSLE_STAFF_2,
    ITEM_ID_MAGICMISSLE_STAFF_3,
    ITEM_ID_FIREBALL_STAFF_1,           
    ITEM_ID_FIREBALL_STAFF_2,
    ITEM_ID_FIREBALL_STAFF_3,
    ITEM_ID_LIGHTNING_STAFF_1,           
    ITEM_ID_LIGHTNING_STAFF_2,
    ITEM_ID_LIGHTNING_STAFF_3,

    ITEM_ID_MUSHROOM,
    ITEM_ID_MUSHROOM_JUICE,

    ITEM_ID_LEATHERBOOTS,
    ITEM_ID_LEATHERVEST,
    ITEM_ID_LEATHERGLOVES,
    ITEM_ID_LEATHERLEGGINGS,

    ITEM_ID_MAGICMMISSLE_SCROLL,
    ITEM_ID_FIREBALL_SCROLL,
    ITEM_ID_LIGHTNING_SCROLL,

    ITEM_ID_APPLE,
    ITEM_ID_CHEESE,
    ITEM_ID_BREAD,
    ITEM_ID_MEAT,

    ITEM_ID_RING,
    ITEM_ID_ERROR,
    ITEM_ID_MAX
};

extern Texture2D g_item_sprites[MAX_SPRITES];
extern Texture2D g_icon_sprites[MAX_SPRITES];


enum SpellID {
    SPELL_ID_NONE = -1,
    SPELL_ID_MAGICMISSLE_1,
    SPELL_ID_MAGICMISSLE_2,
    SPELL_ID_MAGICMISSLE_3,
    SPELL_ID_FIREBALL_1,
    SPELL_ID_FIREBALL_2,
    SPELL_ID_FIREBALL_3,
    SPELL_ID_LIGHTNING_1,
    SPELL_ID_LIGHTNING_2,
    SPELL_ID_LIGHTNING_3,
    SPELL_ID_MAX
};

extern Texture2D g_spell_sprites[MAX_SPRITES];



enum ContainerSprites {
    SPRITE_CONTAINER_CHEST,
    SPRITE_CONTAINER_BARREL,
    SPRITE_CONTAINER_NUM_SPRITES
};

extern Texture2D g_container_sprites[MAX_SPRITES];

enum PortraitSpriteID {
    PORTRAIT_BASE_CHAR,
    PORTRAIT_NUM_SPRITES
};

extern Texture2D g_portrait_sprites[MAX_SPRITES];

enum UIPanelID {
    PANEL_GRAY,
    PANEL_WOOD_LARGE,
    PANEL_NUM_SPRITES,
    PANEL_CHAR_SCREEN
};

extern Texture2D g_ui_panels[MAX_SPRITES];

enum UIBackgroundID {
    BG_SPLASH,
    BG_TITLE,
    BG_STAGING,
    BG_SHELTER,
    BG_HOUSE_TRANS,
    BG_OUTSIDE_TRANS,
    BG_NUM_SPRITES
};

extern Texture2D g_ui_backgrounds[MAX_SPRITES];


enum TileSheetID {
    TS_FOREST,
    TS_SHELTER,
    TS_NUM_SHEETS
};

extern Texture2D g_tile_sheets[MAX_SPRITES];





enum EnvironmentSpriteID {
    SPRITE_ENVIRO_ERROR,
    SPRITE_ENVIRO_TREE1,
    SPRITE_ENVIRO_NUM_SPRITES
};

extern Texture2D g_environment_sprites[MAX_SPRITES];





void LoadResources();


void UnloadResources();
