#pragma once

#include "gamedefs.h"

#define MAX_SPRITES 1000



enum SpriteSheetID {
    SPRITE_APPRENTICE,
    SPRITE_NERD,
    SPRITE_MAIN,
/*     SPRITE_CROSSHAIR,
    SPRITE_WAND,
     */
    SPRITE_NUM_SPRITES
};

extern Texture2D g_sprite_sheets[MAX_SPRITES];

enum UISpriteID {
    UI_ID_CROSSHAIR,
};

extern Texture2D g_ui_sprites[MAX_SPRITES];

enum ItemID {
    ITEM_ID_NONE = -1,
    ITEM_ID_DAGGER,         
    ITEM_ID_SWORD,
    ITEM_ID_SPEAR,
    ITEM_ID_AXE,
    ITEM_ID_BOW,

    ITEM_ID_WAND,
    ITEM_ID_STAFF,

    ITEM_ID_MAGICMISSLE_WAND,           
    ITEM_ID_FIREBALL_WAND,           
    ITEM_ID_LIGHTNING_WAND,

    ITEM_ID_MAGICMISSLE_STAFF,           
    ITEM_ID_FIREBALL_STAFF,           
    ITEM_ID_LIGHTNING_STAFF,           

    ITEM_ID_MUSHROOM,
    ITEM_ID_MUSHROOM_JUICE,

    ITEM_ID_HELMET,
    ITEM_ID_BOOTS,
    ITEM_ID_BODY,
    ITEM_ID_GLOVES,
    ITEM_ID_LEGGINGS,

    ITEM_ID_MAGICMMISSLE_SCROLL,
    ITEM_ID_FIREBALL_SCROLL,
    ITEM_ID_LIGHTNING_SCROLL,

    ITEM_ID_APPLE,
    ITEM_ID_CHEESE,
    ITEM_ID_BREAD,
    ITEM_ID_MEAT,

    ITEM_ID_RING,

    ITEM_ID_STOVE_PLAN,
    ITEM_ID_MUSHROOMPRESS_PLAN,

    ITEM_ID_HAMMER,
    ITEM_ID_SAW,
    ITEM_ID_SHOVEL,
    ITEM_ID_TONGS,
    ITEM_ID_ANVIL,

    ITEM_ID_CHARCOAL,
    ITEM_ID_RESIN,
    ITEM_ID_BONE,
    ITEM_ID_ROPE,
    ITEM_ID_BUCKET,

    ITEM_ID_ERROR,
    ITEM_ID_MAX
};

extern Texture2D g_item_sprites[MAX_SPRITES];
extern Texture2D g_icon_sprites[MAX_SPRITES];


enum RecipieID {
    RECIPIE_ID_NONE = -1,
    RECIPIE_ID_APPLE,
    RECIPIE_ID_WAND,
    RECIPIE_ID_STAFF,
    RECIPIE_ID_MUSHROOMJUICE
};


enum PlanID {
    PLAN_ID_NONE = -1,
    PLAN_ID_STOVE,
    PLAN_ID_MUSHROOMPRESS,
};

enum ItemModID {
    ITEMMOD_NONE = -1,
    ITEMMOD_WEPONSTART,
    ITEMMOD_SWIFTNESS1,
    ITEMMOD_SWIFTNESS2,
    ITEMMOD_SWIFTNESS3,
    ITEMMOD_SWIFTNESS4,
    ITEMMOD_SWIFTNESS5,
    ITEMMOD_DAMAGE1,
    ITEMMOD_DAMAGE2,
    ITEMMOD_DAMAGE3,
    ITEMMOD_DAMAGE4,
    ITEMMOD_DAMAGE5,
    ITEMMOD_WEPONEND,
//
    ITEMMOD_ARMORSTART,
    ITEMMOD_TOUGHNESS1,
    ITEMMOD_TOUGHNESS2,
    ITEMMOD_TOUGHNESS3,
    ITEMMOD_TOUGHNESS4,
    ITEMMOD_TOUGHNESS5,
    ITEMMOD_ARMOREND,

    ITEMMOD_FOODSTART,
    ITEMMOD_NUTRITIOUS,
    ITEMMOD_MOLDY,
    ITEMMOD_FOODEND,
//
    ITEMMOD_MAX
};

enum CharEffectID {
    CHAREFFECT_NONE = -1,
    CHAREFFECT_SPEED1,
    CHAREFFECT_SPEED2,
    CHAREFFECT_SPEED3,
    CHAREFFECT_SPEED4,
    CHAREFFECT_SPEED5,
    
    CHAREFFECT_POISON1,
    CHAREFFECT_POISON2,
    CHAREFFECT_POISON3,
    CHAREFFECT_POISON4,
    CHAREFFECT_POISON5,
//
    CHAREFFECT_MAX
};

enum CharModID {
    CHARMOD_NONE = -1,
    CHARMOD_SPEED1,
    CHARMOD_SPEED2,
    CHARMOD_SPEED3,
    CHARMOD_SPEED4,
    CHARMOD_SPEED5,

    CHARMOD_HEALTH1,
    CHARMOD_HEALTH2,
    CHARMOD_HEALTH3,
    CHARMOD_HEALTH4,
    CHARMOD_HEALTH5,
//
    CHARMOD_MAX
};

enum ModuleID {
    MODULE_ID_NONE = -1,
    MODULE_ID_WORKBENCH,
    MODULE_ID_STOVE,
    MODULE_ID_MUSHROOMPRESS,
};

extern Texture2D g_module_sprites[MAX_SPRITES];

enum SpellID {
    SPELL_ID_NONE = -1,
    SPELL_ID_MAGICMISSLE,
    SPELL_ID_FIREBALL,
    SPELL_ID_LIGHTNING,
    SPELL_ID_MAX
};

extern Texture2D g_spell_sprites[MAX_SPRITES];



enum ContainerSprites {
    SPRITE_CONTAINER_CHEST,
    SPRITE_CONTAINER_BARREL,
    SPRITE_CONTAINER_NUM_SPRITES
};

extern Texture2D g_container_sprites[MAX_SPRITES];

enum PortraitSpriteID {
    PORTRAIT_BASE_CHAR,
    PORTRAIT_NUM_SPRITES
};

extern Texture2D g_portrait_sprites[MAX_SPRITES];

enum UIPanelID {
    PANEL_GRAY,
    PANEL_WOOD_LARGE,
    PANEL_NUM_SPRITES,
    PANEL_CHAR_SCREEN,
    PANEL_MODULE_SCREEN
};

extern Texture2D g_ui_panels[MAX_SPRITES];

enum UIBackgroundID {
    BG_SPLASH,
    BG_TITLE,
    BG_STAGING,
    BG_SHELTER,
    BG_HOUSE_TRANS,
    BG_OUTSIDE_TRANS,
    BG_NUM_SPRITES
};

extern Texture2D g_ui_backgrounds[MAX_SPRITES];


enum TileSheetID {
    TS_FOREST,
    TS_SHELTER,
    TS_NUM_SHEETS
};

extern Texture2D g_tile_sheets[MAX_SPRITES];



enum EnvironmentSpriteID {
    SPRITE_ENVIRO_ERROR,
    SPRITE_ENVIRO_TREE1,
    SPRITE_ENVIRO_TREE2,
    SPRITE_ENVIRO_GRASS1,
    SPRITE_ENVIRO_GRASS2,
    SPRITE_ENVIRO_NUM_SPRITES
};

extern Texture2D g_environment_sprites[MAX_SPRITES];

enum ShadowSpriteID {
    SPRITE_SHADOW_ERROR,
    SPRITE_SHADOW_TREE1,
    SPRITE_SHADOW_TREE2,
    SPRITE_SHADOW_GRASS1,
    SPRITE_SHADOW_GRASS2,
    SPRITE_SHADOW_NUM_SPRITES
};

extern Texture2D g_shadow_sprites[MAX_SPRITES];



void LoadResources();


void UnloadResources();
